USE TIENDA;

SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio*1.12  FROM producto;
SELECT nombre AS `nom de producto`, precio AS `euros`, precio*1.12 AS `dolars` FROM producto;
SELECT UPPER (nombre), precio FROM producto;
SELECT LOWER (nombre), precio FROM producto;
SELECT nombre, UPPER (left (nombre,2)) FROM fabricante;
SELECT nombre, ROUND(precio), precio FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT codigo_fabricante FROM producto GROUP BY codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT * FROM fabricante  JOIN producto WHERE fabricante.codigo = '2';
SELECT producto.nombre AS nombreProducto, producto.precio AS precioProducto, fabricante.nombre AS nombreFabricante FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;

USE UNIVERSIDAD;
SELECT apellido1, apellido2, nombre FROM persona ORDER BY apellido1, apellido2, nombre ASC;
SELECT apellido1, apellido2, nombre, telefono FROM persona WHERE telefono IS NULL;
SELECT apellido1, apellido2, fecha_nacimiento FROM persona;
SELECT nombre, tipo, telefono, nif FROM persona WHERE nif LIKE '%K' AND tipo = 'profesor' AND telefono IS NULL;
SELECT nombre, cuatrimestre, curso, id_grado FROM asignatura WHERE cuatrimestre = '1' AND curso = '3' AND id_grado = '7';
SELECT persona.apellido1, persona.apellido2, persona.nombre AS persona_nombre, departamento.nombre AS departamento_nombre FROM profesor INNER JOIN departamento ON profesor.id_departamento = departamento.id INNER JOIN persona ON profesor.id_profesor = persona.id ORDER BY persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM alumno_se_matricula_asignatura INNER JOIN asignatura ON alumno_se_matricula_asignatura.id_asignatura = asignatura.id INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id INNER JOIN persona ON alumno_se_matricula_asignatura.id_alumno = persona.id WHERE persona.nif = '26902806M';
SELECT departamento.nombre FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento INNER JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id_grado = '4';
SELECT * FROM persona INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.id = '5';
SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN departamento ON persona.id = departamento.id WHERE persona.tipo = 'profesor' ORDER BY departamento.nombre ASC, persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN departamento ON persona.id = departamento.id WHERE persona.tipo = 'profesor' AND departamento.nombre IS NULL ORDER BY departamento.nombre ASC, persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT * FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento WHERE id_profesor IS NULL;
SELECT asignatura.id AS id_asignatura, persona.nombre, persona.apellido1, persona.apellido2, persona.nif, persona.tipo FROM  asignatura RIGHT JOIN persona ON asignatura.id_profesor = persona.id WHERE asignatura.id_profesor IS NULL AND persona.tipo = 'profesor';
SELECT nombre, id_profesor FROM asignatura WHERE id_profesor IS NULL;
SELECT DISTINCT departamento.nombre AS departamento FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id IS NULL;
SELECT COUNT(*) FROM persona WHERE tipo = 'alumno';
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31';
SELECT departamento.nombre, COUNT(profesor.id_profesor) AS numero_profesores FROM profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id GROUP BY profesor.id_departamento ORDER BY numero_profesores DESC;
SELECT departamento.nombre, COUNT(profesor.id_departamento) AS numero_profesores FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.id;
SELECT grado.id, grado.nombre, COUNT(asignatura.id) AS numero_asignaturas FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.id ORDER BY numero_asignaturas DESC;
SELECT grado.id, grado.nombre, COUNT(asignatura.id) AS numero_asignaturas FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado  GROUP BY grado.id HAVING COUNT(asignatura.id) > 40;
SELECT grado.id, grado.nombre, sum(asignatura.creditos) AS numero_asignaturas FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado  GROUP BY grado.nombre;
